### ISSUE TITLE
Likely bug in MC and CC

### ISSUE THREAD

**Issue by mlubin** [joehuchette/PiecewiseLinearOpt.jl#1]
I've run some tests on 4 different instances. I had previously implemented the straightforward extended formulation for the V-disjunction. ``Incremental`` and ``Logarithmic`` give consistent objective values with my current models. ``MC`` and ``CC`` both seem to give incorrect values, suggesting a bug. Is this expected?

**Comment by joehuchette** [comment]
Let me know if 607539b714f6595e196863ceed572b7f996b3acb fixes the discrepancies.

**Comment by mlubin** [comment]
Seems to be fixed from preliminary tests, will reopen if not.
