### ISSUE TITLE
log(x)+log(y)+log(z)

### ISSUE THREAD

**Issue by stumarcus314** [joehuchette/PiecewiseLinearOpt.jl#17]

**Comment by stumarcus576** [comment]
I believe, the following code will construct the piecewise linearization of a separable function depending on multiple independent variables such as: log x + log y + log z. How does one get the d^x, d^y, etc. to show up in the Julia test code (i.e. the superscripts)?

using PiecewiseLinearOpt
using JuMP, Cbc

const solver = CbcSolver()
methods_1D = (:CC,:MC,:Logarithmic,:ZigZag,:ZigZagInteger,:SOS2,:GeneralizedCelaya,:SymmetricCelaya,:Incremental)

let dx = linspace(2,2π,8), dy = linspace(3,2π,7), dz = linspace(3,2π,9), f = log
    for method in methods_1D
        println("Method: $method")
        m = Model(solver=solver)
        @variable(m, x)
        @variable(m, y)
        @variable(m, z)
        log_x = piecewiselinear(m, x, dx, f, method=method)
        log_y = piecewiselinear(m, y, dy, f, method=method)
        log_z = piecewiselinear(m, y, dz, f, method=method)
        @objective(m, Min, log_x+log_y+log_z)
        solve(m) == :Optimal

        println("Objective Value: ", exp(getobjectivevalue(m)))
        println("log x = ", exp(getvalue(log_x)))
        println("log y = ", exp(getvalue(log_y)))
        println("log z = ", exp(getvalue(log_z)))

    end
end

**Comment by stumarcus576** [comment]
The code below is better:

using PiecewiseLinearOpt
using JuMP, Cbc

# Minimize volume = x*y*z by minimizing log(x*y*z) = log(x)+log(y)+log(z) through piecewise univariate linearization of log(x), log(y), and log(z).

const solver = CbcSolver()
#const solver = GurobiSolver()
methods_1D = (:CC,:MC,:Logarithmic,:ZigZag,:ZigZagInteger,:SOS2,:GeneralizedCelaya,:SymmetricCelaya,:Incremental)

let dx = linspace(5,2π,8), dy = linspace(4,2π,7), dz = linspace(3,2π,9), f = log
    for method in methods_1D
        println("Method: $method")
        m = Model(solver=solver)
        @variable(m,x)
        @variable(m,y)
        @variable(m,z)
        log_x = piecewiselinear(m,x,dx,f,method=method)
        log_y = piecewiselinear(m,y,dy,f,method=method)
        log_z = piecewiselinear(m,z,dz,f,method=method)
        @objective(m,Min,log_x+log_y+log_z)
        solve(m) == :Optimal

        println("Volume: ",exp(getobjectivevalue(m)))
        println("x = ",exp(getvalue(log_x)))
        println("y = ",exp(getvalue(log_y)))
        println("z = ",exp(getvalue(log_z)))

    end
end
