### ISSUE TITLE
Single method

### ISSUE THREAD

**Issue by stumarcus314** [joehuchette/PiecewiseLinearOpt.jl#20]
How does one set just a single method to test using the method for loop test code? For example,
methods_1D = (:Logarithmic)
doesn't work, giving the error below:

ERROR: LoadError: MethodError: no method matching start(::Symbol)
Closest candidates are:
  start(!Matched::SimpleVector) at essentials.jl:258
  start(!Matched::Base.MethodList) at reflection.jl:560
  start(!Matched::ExponentialBackOff) at error.jl:107
  ...
Stacktrace:
 [1] anonymous at ./<missing>:?
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] process_options(::Base.JLOptions) at ./client.jl:305
 [5] _start() at ./client.jl:371
while loading /Users/a598124/juliaCode/boxPacking1/monroe6.jl, in expression starting on line 16

**Comment by joehuchette** [comment]
```jl
@show typeof( (:Logarithmic) ) # Symbol
@show typeof( (:Logarithmic,) ) # Tuple{Symbol}
```

This is about julia, not specific to this package, so please direct them elsewhere in the future(e.g. [discourse](https://discourse.julialang.org)).
