### ISSUE TITLE
info on main page about supported bivariate methods

### ISSUE THREAD

**Issue by stumarcus314** [joehuchette/PiecewiseLinearOpt.jl#22]
Why does the main package page (https://github.com/joehuchette/PiecewiseLinearOpt.jl) only say that  supported bivariate formulations include Convex Combination, Multiple Choice, and Dissaggregated Logarithmic? Why doesn't the main page mention the other bivariate methods :Logarithmic,:LogarithmicIB,:ZigZag,:ZigZagInteger,:SOS2,:GeneralizedCelaya,:SymmetricCelaya, which appear in methods_2D in runtests.jl?

**Comment by joehuchette** [comment]
The last paragraph was intended to convey this, but I'll change it so that it's clearer.
