### ISSUE TITLE
Move to JuMP-dev and adopt as a proper package

### ISSUE THREAD

**Issue by odow** [joehuchette/PiecewiseLinearOpt.jl#49]
Should we do this? It seems like this package could be useful to many users, but it isn't well advertised, and @joehuchette likely doesn't have the bandwidth to maintain it properly at the moment.

**Comment by jd-foster** [comment]
I think this makes sense - I would like to offer to help with maintenance if Joey agrees.

**Comment by joehuchette** [comment]
Happy to transfer to JuMP-dev! And glad to hear that there’s interest in giving this package the maintenance that it deserves, @jd-foster — much appreciated.

**Comment by odow** [comment]
@hellemo and @trulsf have been working on https://github.com/sintefore/PiecewiseAffineApprox.jl (with slightly different goals), so I think there is some interest in combining the two packages and having a robustly supported and maintained package for this sort of thing.

@joehuchette you'll have permission to move it. Go to https://github.com/joehuchette/PiecewiseLinearOpt.jl/settings and then there's a red "transfer" button at the bottom.

**Comment by joehuchette** [comment]
Done!

**Comment by odow** [comment]
Registry updated here: https://github.com/JuliaRegistries/General/pull/114969
