### ISSUE TITLE
depends on JuMP 0.16

### ISSUE THREAD

**Issue by mlubin** [joehuchette/PiecewiseLinearOpt.jl#5]
The syntax at https://github.com/joehuchette/PiecewiseLinearOpt.jl/blob/1b68ee8bef77e207d1c3b792cbc48c963ab50e73/src/jump.jl#L198 is only available in JuMP 0.16. REQUIRE needs a bump.

**Comment by joehuchette** [comment]
Closed by 7bfe1bc1bdd56c855c4bd98d727368af8cf4bd44
